export interface QuizEntry {
  texto: string;
  correto: boolean;
}

export const QUIZ_DATA: QuizEntry[] = [
  // ── VERDADEIRO ────────────────────────────────────────────────────────────────
  { correto: true,  texto: "[GLA] A habilidade Liberation, do Marshall D. Teach, tem dois segundos de tempo de recarga e 18 de poder." },
  { correto: true,  texto: "[GLA] A habilidade Preparation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque." },
  { correto: true,  texto: "[GLA] Baratie e recomendado para jogadores do level 42 a 52 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] A habilidade Usopp Fear concede velocidade e defesa para ele." },
  { correto: true,  texto: "[GLA] A rotação semanal muda toda sexta-feira." },
  { correto: true,  texto: "[GLA] Baratie é o primeiro local em que você pode construir um navio nível 3." },
  { correto: true,  texto: "[GLA] Bartholomew Kuma lê sua bíblia durante a animação do seu emote." },
  { correto: true,  texto: "[GLA] Boa Hancock não pode petrificar o Monkey D. Luffy." },
  { correto: true,  texto: "[GLA] Boa Hancock pode transformar os inimigos em pedra por 7 segundos com a habilidade Mero Mero Mellow." },
  { correto: true,  texto: "[GLA] Cabaji tem a menor velocidade de movimento base do jogo." },
  { correto: true,  texto: "[GLA] Camisa de Tritão é o item mais caro que o Genzo Vende e custa 10000 berry." },
  { correto: true,  texto: "[GLA] Capone Gang Bege é o único personagem que pode convocar dois subordinados sem esperar o tempo de recarga." },
  { correto: true,  texto: "[GLA] Capone Gang Bege não libera nenhuma habilidade no nível 100." },
  { correto: true,  texto: "[GLA] Chabo é o nome da criança que a Nojiko pede para ajudar no Arlong Park." },
  { correto: true,  texto: "[GLA] Chopper ganha defesa bônus durante a habilidade Walk Point." },
  { correto: true,  texto: "[GLA] Cocoyasi Village é recomendado para jogadores do level 50 a 60 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] É obrigatório derrotar o Jango na missão do Black Cat no modo história." },
  { correto: true,  texto: "[GLA] É possível criar Medalhas Dinâmicas de Bronze por 5 Moedas Piratas no Mercado Negro." },
  { correto: true,  texto: "[GLA] É possível criar Medalhas Dinâmicas de Diamante por 40 Moedas Piratas no Mercado Negro." },
  { correto: true,  texto: "[GLA] É possivel criar Medalhas Dinâmicas de Ouro por 20 Moedas Piratas no Mercado Negro." },
  { correto: true,  texto: "[GLA] É possivel criar Medalhas Dinâmicas de Prata por 10 Moedas Piratas no Mercado Negro." },
  { correto: true,  texto: "[GLA] É possível fazer missões diárias de Tritão em Cocoyasi Village" },
  { correto: true,  texto: "[GLA] É possível preparar algumas comidas na casa da Nojiko." },
  { correto: true,  texto: "[GLA] É possível reparar os equipamentos do seu navio nas Docas." },
  { correto: true,  texto: "[GLA] Em Cocoyasi Village, você pode comprar Laranja no NPC por 42 berries cada." },
  { correto: true,  texto: "[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 20." },
  { correto: true,  texto: "[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 30." },
  { correto: true,  texto: "[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 12." },
  { correto: true,  texto: "[GLA] Em regra, emotes são desbloqueados no nível 25." },
  { correto: true,  texto: "[GLA] Erros no jogo devem ser reportados usando o atalho CTRL+R." },
  { correto: true,  texto: "[GLA] Existem 28 conquistas para completar no Modo história das missões especiais do East Blue." },
  { correto: true,  texto: "[GLA] Existem Bronze Berry, Silver Berry, Gold Berry e Platinum Berry." },
  { correto: true,  texto: "[GLA] Existem Cows, Pigs, Chickens e Sheeps em Foosha Village." },
  { correto: true,  texto: "[GLA] Existem dois baús de ouro em Loguetown." },
  { correto: true,  texto: "[GLA] Fuyuki é o avô do sora." },
  { correto: true,  texto: "[GLA] Genzo vende Bandana de Tritão, Calça de Tritão, Anel do Mar e Turbante do Mar por 5200 berry cada." },
  { correto: true,  texto: "[GLA] Golden Hull é o nome de uma Skin de Navio." },
  { correto: true,  texto: "[GLA] Há 8 Henchman no Mercado Negro." },
  { correto: true,  texto: "[GLA] Há um baú escondido atrás da mansão da Kaya." },
  { correto: true,  texto: "[GLA] Há um mapa na casa da Nojiko." },
  { correto: true,  texto: "[GLA] Há uma piscina em Shells Town, dentro da Base da Marinha." },
  { correto: true,  texto: "[GLA] Há uma prisioneira chamada Tina no Arlong Park." },
  { correto: true,  texto: "[GLA] Island of Rare Animals é recomendada para jogadores do level 40 a 52 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] Jose, discípulo de Carmen, está na biblioteca em Loguetown." },
  { correto: true,  texto: "[GLA] Jutte Blow, a habilidade do Smoker, silencia somente usuários de Fruta do Diabo." },
  { correto: true,  texto: "[GLA] Kumo Island é recomendada para jogadores do level 64 a 72 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] Kuro causa 20% a mais de dano quando ataca inimigos pelas costas." },
  { correto: true,  texto: "[GLA] Loguetown é recomendada para jogadores do level 60 a 70 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] Marshall D. Teach ganha 25% de ataque e perde metade da armadura quando sua passiva é ativada." },
  { correto: true,  texto: "[GLA] Mohji perde energia enquanto está em batalha." },
  { correto: true,  texto: "[GLA] Monkey D. Luffy não pode quebrar paredes com a habilidade Gomu Gomu no Ono." },
  { correto: true,  texto: "[GLA] Nami não pode usar a habilidade Fata Morgana enquanto Mirage Tempo estiver ativa." },
  { correto: true,  texto: "[GLA] Não é possível subir no segundo andar da loja do Ippon-Matsu em Loguetown." },
  { correto: true,  texto: "[GLA] Nico Robin pode construir pontes com a habilidade Campo de Flores." },
  { correto: true,  texto: "[GLA] Nico Robin pode construir pontes com a habilidade Delphinium." },
  { correto: true,  texto: "[GLA] Ninjin, um dos Piratas do Usopp, dá uma missão em Syrup Village." },
  { correto: true,  texto: "[GLA] O jogo está traduzido para os seguintes idiomas: Inglês, Português, Espanhol e Polonês." },
  { correto: true,  texto: "[GLA] O jogo Grand Line Adventures foi lançado em Agosto de 2018." },
  { correto: true,  texto: "[GLA] O Kit de Reparo 2.0 restaura 22.500 pontos de vida do seu navio em 20 segundos." },
  { correto: true,  texto: "[GLA] O Kit de Reparo 2.0 restaura 1125 pontos de vida do seu navio por segundo." },
  { correto: true,  texto: "[GLA] O Kit de Reparo 3.0 restaura 36.000 pontos de vida do seu navio em 20 segundos." },
  { correto: true,  texto: "[GLA] O Kit de Reparo 3.0 restaura 1800 pontos de vida do seu navio por segundo." },
  { correto: true,  texto: "[GLA] O nome de todas as habilidades do Capone Gang Bege começam com a letra C, exceto o Big Father." },
  { correto: true,  texto: "[GLA] O PvP na Grand Line será opcional" },
  { correto: true,  texto: "[GLA] O Sangramento do Alligator selvagem também reduz a velocidade de movimento do personagem." },
  { correto: true,  texto: "[GLA] O Stash VIP tem 100 espaços para itens." },
  { correto: true,  texto: "[GLA] O Talismã da Aranha é um item que pode ser usado por todas as classes." },
  { correto: true,  texto: "[GLA] O uso do Kit de Reparo é interrompido se você receber qualquer ataque de um inimigo." },
  { correto: true,  texto: "[GLA] Orange Town é recomendada para jogadores do level 23 a 30 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] Para melhorar um personagem de 1 para 5 estrelas você precisa usar 840 medalhas no total." },
  { correto: true,  texto: "[GLA] Pearl é o primeiro boss na missão da Armada Pirata." },
  { correto: true,  texto: "[GLA] Pearl não pode usar nenhuma habilidade enquanto Iron Wall estiver ativo." },
  { correto: true,  texto: "[GLA] Personagens Diamante são 7% mais fortes que personagens Ouro." },
  { correto: true,  texto: "[GLA] Personagens envenenados pela Reiju recebem 50% menos cura de Suportes." },
  { correto: true,  texto: "[GLA] Portgas D. Ace é um personagem Diamante." },
  { correto: true,  texto: "[GLA] Quando um Alligator selvagem morre, o sangramento aplicado por ele perde o efeito." },
  { correto: true,  texto: "[GLA] Reiju pode usar sua habilidade Pink Tornado para se livrar de imobilizações." },
  { correto: true,  texto: "[GLA] Samui Island é recomendada para jogadores do level 20 a 28 no minimapa do jogo." },
  { correto: true,  texto: "[GLA] Sanji não pode ser seduzido pelas mulheres enquanto o Diable Jamble estiver ativado." },
  { correto: true,  texto: "[GLA] Sapi é o NPC que vende Atum em Loguetown." },
  { correto: true,  texto: "[GLA] Sayuri, Asuya e Chieri são nomes de NPCs do Baratie." },
  { correto: true,  texto: "[GLA] Skins de navio estão disponiveis somente para navios de nivel dois ou maior." },
  { correto: true,  texto: "[GLA] Snowball é o nome de um coelho em Samui Island." },
  { correto: true,  texto: "[GLA] Syrup Village é a ilha com o maior número de entradas de doca no East Blue." },
  { correto: true,  texto: "[GLA] Tamanegi, um dos piratas do Usopp, dá algumas missões em Syrup Village." },
  { correto: true,  texto: "[GLA] Trafalgar Law pode quebrar paredes com a habilidade Injection Shot." },
  { correto: true,  texto: "[GLA] Urouge pode usar a Habilidade Pray para curar aliados e também remover condições de lentidão ou queimadura." },
  { correto: true,  texto: "[GLA] Você não pode trocar seus equipamentos em batalha." },
  { correto: true,  texto: "[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 15 gemas e a segunda 30 gemas." },
  { correto: true,  texto: "[GLA] Você pode construir uma Caixa de Música no Mercado Negro." },
  { correto: true,  texto: "[GLA] Você pode encontrar 9 entradas para o Mercado Negro no East Blue." },
  { correto: true,  texto: "[GLA] Você pode ouvir o Chouchou latindo ao falar com ele." },
  { correto: true,  texto: "[GLA] Você pode usar o atalho ALT + ENTER para colocar o jogo em tela cheia." },
  { correto: true,  texto: "[GLA] Você precisa alimentar um prisioneiro na Quest da Rika." },
  { correto: true,  texto: "[GLA] Você precisa vencer com um time de especialistas para completar a conquista dos Black Cat." },
  { correto: true,  texto: "[GLA] Você precisa vencer com um time de lutadores para completar a conquista dos Piratas do Buggy." },
  { correto: true,  texto: "[GLA] Você precisa vencer com um time de chapéus de palha para completar a conquista dos Piratas do Arlong." },
  { correto: true,  texto: "[GLA] Você precisa vencer com um time de usuários de Fruta do Diabo para completar a conquista da Base da Marinha." },
  { correto: true,  texto: "[GLA] Você precisa vencer com uma equipe de mulheres para completar a conquista da Armada Pirata." },
  { correto: true,  texto: "[GLA] Whale Shark é considerado um monstro nível 3." },
  { correto: true,  texto: "A alcunha do Doc Q, shinigami ou deus da morte, vem do fato dele gostar de brincar com a vida das pessoas, assim como um shinigami." },
  { correto: true,  texto: "A atual recompensa do Bepo é de 500 berry." },
  { correto: true,  texto: "A cera do Mr. 3 é tão dura quanto o aço." },
  { correto: true,  texto: "A comida favorita da Sugar é uva." },
  { correto: true,  texto: "A comida favorita de Kuro é banana." },
  { correto: true,  texto: "A comida favorita do Doflamingo é lagosta." },
  { correto: true,  texto: "A comida favorita do Marco é abacaxi." },
  { correto: true,  texto: "A comida favorita do Nezumi é queijo." },
  { correto: true,  texto: "A cor do cabelo da mãe da Nico Robin é branco." },
  { correto: true,  texto: "A dubladora do Chopper foi alterada em alguns episódios." },
  { correto: true,  texto: "A espada de Shiliew é uma Meito chamada \"Raiu\"." },
  { correto: true,  texto: "A espada do Shiryu é uma Meito chamada \"Raiu\"." },
  { correto: true,  texto: "A Gura Gura no Mi é também conhecida como a mais forte das Paramecia, igual a uma Logia. Sengoku afirmou que ela é poderosa o suficiente para destruir o mundo." },
  { correto: true,  texto: "A irmã do Arlong é conhecida." },
  { correto: true,  texto: "A mãe do Monkey D. Luffy ainda não foi revelada." },
  { correto: true,  texto: "A Ope Ope no Mi é também chamada da Fruta do Diabo Suprema, devido a sua habilidade de conceder vida eterna." },
  { correto: true,  texto: "A personagem Boa Hancock possui várias referências a mitologia Grega." },
  { correto: true,  texto: "A primeira recompensa da Nico Robin foi de 79,000,000 de berry, a mesma quantia de sua mãe Nico Olvia." },
  { correto: true,  texto: "A primeira recompensa do Monkey D. Luffy foi de 30,000,000 de berry." },
  { correto: true,  texto: "A primeira recompensa do Tony Tony Chopper foi de 50 berry." },
  { correto: true,  texto: "A quarta recompensa do Monkey D. Luffy foi de 400,000,000 de berry." },
  { correto: true,  texto: "A recompensa da Curly Dadan é de 7,800,000 de berry." },
  { correto: true,  texto: "A recompensa da Miss Doublefinger é de 35.000.000 berries." },
  { correto: true,  texto: "A recompensa da Miss Goldenweek é de 29,000,000 de berry." },
  { correto: true,  texto: "A recompensa da Miss Merry Christmas é de 14,000,000 de berry." },
  { correto: true,  texto: "A recompensa da Miss Valentine é de 7,500,000 de berry." },
  { correto: true,  texto: "A recompensa de Daz Bones é de 75,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Lao G era de 61,000,000 de berry antes de ser congelado em razãp do Doflamingo ter se tomado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Machvise era de 11,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Mont Blanc Cricket é de 25,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Mr. 2 é de 32,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Mr. 3 é de 24,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Mr. 4 é de 3,200,000 de berry." },
  { correto: true,  texto: "A recompensa do Mr. 5 é de 10,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Pica era de 99,000,000 de berry antes de ser con gelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Senor Pink era de 58,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Tamago é de 429,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Trebol era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do X-Drake é de 222,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Zoro era maior que a do Sanji." },
  { correto: true,  texto: "A recompensa dos Irmãos Nyaban é de 7,000,000 de berry." },
  { correto: true,  texto: "A Rumble Ball dura 3 minutos." },
  { correto: true,  texto: "A segunda recompensa conhecida do Capone Gang Bege era de 300,000,000 de berry." },
  { correto: true,  texto: "A segunda recompensa de Monkey D. Luffy foi de 100.000.000 de berries." },
  { correto: true,  texto: "A Yubashiri (Espada de Zoro) Enferrujou." },
  { correto: true,  texto: "A Yubashiri (uma das espadas do Zoro) enferrujou." },
  { correto: true,  texto: "Ace realmente nasceu em Baterilla." },
  { correto: true,  texto: "Aisa nasceu com um Haki da Observação avançado." },
  { correto: true,  texto: "Akainu tem o mesmo dublador do Krieg." },
  { correto: true,  texto: "Aladdin já foi um escravo." },
  { correto: true,  texto: "Alvida é a antiga capitã dos Piratas da Alvida." },
  { correto: true,  texto: "A recompensa de Kuroobi é de 9,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Bartholomew Kuma é de 296,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Capone Gang Bege é de 300.000.000 berries." },
  { correto: true,  texto: "A recompensa do Chew é de 5,500,000 de berry." },
  { correto: true,  texto: "A recompensa do Dellinger era de 15,000,000 de berry antes de congelada em razão do Doflamingo ter se tornado Shichibukai." },
  { correto: true,  texto: "A recompensa do Demaro Black é de 26,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Diamante era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Donquixote Doflamingo é de 340,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Fisher Tiger era de 230,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Foxy é de 24,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Gecko Moria é de 320,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Gin é de 12,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Gladius era de 31,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: true,  texto: "A recompensa do Jinbe era de 250,000,000 de berry antes dele se tornar um Shichibukai." },
  { correto: true,  texto: "A recompensa do Killer é de 200,000,000 de berry." },
  { correto: true,  texto: "A recompensa do Kuro é de 16,000,000 de berry." },
  { correto: true,  texto: "Antes dos eventos da guerra, Doc Q tinha uma impressionante recompensa de 72,000,000 de berry." },
  { correto: true,  texto: "Antes dos eventos da guerra, Jesus Burguess tinha uma recompensa de 20,000,000 de berry." },
  { correto: true,  texto: "Antes dos eventos da guerra, Laffitte tinha uma recompensa de 42,200,000 de berry." },
  { correto: true,  texto: "Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 64,000,000 de Berry." },
  { correto: true,  texto: "Aokiji tem uma Fruta do Diabo do tipo Logia." },
  { correto: true,  texto: "Apesar da aparência deles, Masira e Shoujo são humanos." },
  { correto: true,  texto: "Após a morte do Barba Branca, o Barba Marrom fugiu e assumiu o controle de Foodvalten." },
  { correto: true,  texto: "Após os eventos em Punk Hazard, Smoker se tornou oficialmente o líder da G-5." },
  { correto: true,  texto: "Após ser diagnosticado com sua doença, Gol D. Roger levou três anos para encontrar o One Piece." },
  { correto: true,  texto: "Arlong é o único indivíduo conhecido que foi liberado de Impel Down." },
  { correto: true,  texto: "Arlong era o capitão dos Piratas do Arlong e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy." },
  { correto: true,  texto: "Assim como Fujitora, Smoker deseja acabar com o sistema de Shichibukai." },
  { correto: true,  texto: "Atualmente Moria é o único Shichibukai conhecido (atual ou antigo) sem uma alcunha conhecida." },
  { correto: true,  texto: "Avalo Pizarro é o capitão do quarto navio, liderando a quarta frota do Teach." },
  { correto: true,  texto: "Avalo Pizarro era originalmente rei de um país no North Blue." },
  { correto: true,  texto: "Baby Five nasceu no North Blue." },
  { correto: true,  texto: "Barba Branca nasceu na Sphinx Island no Novo Mundo." },
  { correto: true,  texto: "Barba Negra acredita legitimamente que os sonhos dos homens nunca morrerão." },
  { correto: true,  texto: "Barba Negra é um Almirante dos Piratas do Barba Negra e membro dos Yonkou." },
  { correto: true,  texto: "Barba Negra nasceu na Grand Line." },
  { correto: true,  texto: "Bartholomew Kuma é conhecido como o Tirano." },
  { correto: true,  texto: "Bartholomew Kuma e um Shichibukai e um ex-oficial do Exercito Revolucionario." },
  { correto: true,  texto: "Bartholomew Kuma já foi um Rei." },
  { correto: true,  texto: "Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Hawkins." },
  { correto: true,  texto: "Bellamy se aposentou oficialmente como um pirata e agora se dedica a pintura de bandeiras." },
  { correto: true,  texto: "Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no East Blue." },
  { correto: true,  texto: "Benn Beckman é o personagem mais inteligente que apareceu na saga do East Blue." },
  { correto: true,  texto: "Benn Beckman é o vice-capitão dos Piratas do Ruivo." },
  { correto: true,  texto: "Benn Beckman nasceu no North Blue." },
  { correto: true,  texto: "Boa Hancock é a capitã das Piratas Kuja e a única mulher membro dos Shichibukai." },
  { correto: true,  texto: "Boa Hancock usa Haki do Rei." },
  { correto: true,  texto: "Boa Marigold e Boa Sandersonia têm Haki da Observação e do Armamento." },
  { correto: true,  texto: "Brook é mais alto que o Franky depois do Timeskip." },
  { correto: true,  texto: "Brook era o capitão dos Rumbar Pirates." },
  { correto: true,  texto: "Buffalo nasceu no North Blue." },
  { correto: true,  texto: "Buggy é capitão dos Piratas do Buggy e também colíder da Aliança do Buggy e Alvida." },
  { correto: true,  texto: "Buggy era um Shichibukai." },
  { correto: true,  texto: "Buggy foi o primeiro vilão a aparecer na série que era usuário de uma Fruta do Diabo. Ele foi também o primeiro usuário de uma Fruta do Diabo com quem Luffy lutou." },
  { correto: true,  texto: "Buggy tem a menor recompensa conhecida entre os Shichibukai." },
  { correto: true,  texto: "Cada um dos quatro principais membros da tripulação do Shanks são de diferentes oceanos." },
  { correto: true,  texto: "Caesar comeu a Gasu Gasu no Mi." },
  { correto: true,  texto: "Caesar liberou um gás não letal em Punk Hazard." },
  { correto: true,  texto: "Capone Gang Bege é capitão do Fire Tank Pirates e também um dos doze piratas classificados como a Pior Geração." },
  { correto: true,  texto: "Caribou nasceu no North Blue." },
  { correto: true,  texto: "Carina era amiga da Nami no East Blue." },
  { correto: true,  texto: "Caso o Governo Mundial soubesse que o Crocodile era o chefe da Baroque Works, a recompensa dele seria no mínimo dobrada para 162,000,000 de berry." },
  { correto: true,  texto: "Caso o One Piece fosse ambientado no mundo real, o Luffy seria do Brasil." },
  { correto: true,  texto: "Catarina Devon caça qualquer MULHER que ela acha atraente e decapita a cabeça para adicionalas a sua coleção pessoal." },
  { correto: true,  texto: "Catarina Devon é a capitã do sexto navio, liderando a sexta frota do Teach." },
  { correto: true,  texto: "Chopper experimentou algodão doce pela primeira vez durante o Davy Back Fight." },
  { correto: true,  texto: "Chopper foi o sexto membro a entrar na tripulação dos Chapéus de Palha." },
  { correto: true,  texto: "Crocodile é o unico Shichibukai a possuir uma fruta tipo Logia." },
  { correto: true,  texto: "Crocodile foi o primeiro oponente a derrotar Luffy em uma batalha." },
  { correto: true,  texto: "Crocodile nasceu na Grand Line." },
  { correto: true,  texto: "Crocus nasceu na Grand Line." },
  { correto: true,  texto: "Daddy Masterson é um personagem non-canon." },
  { correto: true,  texto: "Dalton nasceu em Drum Island." },
  { correto: true,  texto: "Demaro Black nasceu no East Blue." },
  { correto: true,  texto: "Demaro Black, capitão dos Falsos Chapéu de Palha, nasceu no East Blue." },
  { correto: true,  texto: "Demaro Black, Manjaro, Chocolat, Drip, Turco, Cocoa, Mountblutain e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos Chapéus de Palha." },
  { correto: true,  texto: "Desde quando Mr. 1 era uma criança, ele sempre quis ser um herói. Todavia, os ideais dele se distorceram bastante, transformando-o em um assassino implacável." },
  { correto: true,  texto: "Diamante é usuário do Haki da Observação e do Armamento." },
  { correto: true,  texto: "Diamond Jozu comeu a Kira Kira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável." },
  { correto: true,  texto: "Dizem que Yasopp pode atirar na antena de uma formiga de muito longe." },
  { correto: true,  texto: "Doc Q é o médico dos Piratas do Barba Negra." },
  { correto: true,  texto: "Doflamingo é Usuário do Haki Da Observação, Armamento e do Rei." },
  { correto: true,  texto: "Doflamingo e Viola tiveram uma complexa relação amorosa." },
  { correto: true,  texto: "Doflamingo era Capitão dos Piratas Donquixote." },
  { correto: true,  texto: "Doflamingo era um Tenryubito." },
  { correto: true,  texto: "Dorry nasceu em Elbaf." },
  { correto: true,  texto: "Edward Newgate é loiro." },
  { correto: true,  texto: "Eiichiro Oda é o criador do One Piece." },
  { correto: true,  texto: "Em alguns fillers, os personagens foram feitos pelo próprio Oda." },
  { correto: true,  texto: "Em razão dos seus crimes, Sanjuan Wolf foi preso em Impel Down. O modo que eles encontraram para mantê-lo preso foi através de uma cela gigante no level 6." },
  { correto: true,  texto: "Em termos simples, Haki é a habilidade de sentir energia espiritual (Kenbunshoku), usar força vital (Busoshoku) e dominar inimigos (Haoshoku)." },
  { correto: true,  texto: "Emporio Ivankov nasceu na Grand Line." },
  { correto: true,  texto: "Enel está na lua." },
  { correto: true,  texto: "Enquanto a fruta do Borsalino é sobre velocidade ele é bastante lento quando se trata de falar ou agir." },
  { correto: true,  texto: "Eustass Kid perdeu seu braço esquerdo." },
  { correto: true,  texto: "Existem Frutas do Diabo que ainda não foram catalogadas e, portanto, desconhecidas." },
  { correto: true,  texto: "Foi confirmado que Usopp despertou o Haki da Observação durante o Arco de Dressrosa." },
  { correto: true,  texto: "Foxy comeu a Noro Noro no Mi." },
  { correto: true,  texto: "Foxy nasceu no South Blue." },
  { correto: true,  texto: "Franky é o oitavo membro a entrar no Bando dos Chapéus de Palha." },
  { correto: true,  texto: "Gedatsu (um dos sacerdotes de Enel) agora gerencia um Resort de águas termais em Alabasta." },
  { correto: true,  texto: "Gryphon é o nome da espada do Shanks." },
  { correto: true,  texto: "Gin é um pirata e membro dos Piratas do Krieg." },
  { correto: true,  texto: "Giolla criou Dellinger praticamente sozinha, fazendo com que ele pensasse que era uma menina, razão pela qual ele se tornou tão afeminado." },
  { correto: true,  texto: "Gol D. Roger foi o primeiro Rei dos Piratas." },
  { correto: true,  texto: "Gol D. Roger nasceu em Loguetwon." },
  { correto: true,  texto: "Gum-Gum Fruit é o nome oficial da Fruta do Diabo do Luffy em Inglês." },
  { correto: true,  texto: "Há seis Níveis em Impel Down." },
  { correto: true,  texto: "Há um Tritão na Família Donquixote." },
  { correto: true,  texto: "Haki é um misterioso poder que se encontra dentro de todos os seres vivos do mundo." },
  { correto: true,  texto: "Hancock é a imperatriz do Amazon Lily, motivo pelo qual ela é chamada de Imperatriz Pirata." },
  { correto: true,  texto: "Hancock é a primeira personagem mulher da série capaz de usar todas as três formas de Haki." },
  { correto: true,  texto: "Hatchan é um ex-oficial dos Piratas do Arlong e membro dos Piratas do Sol antes disso." },
  { correto: true,  texto: "Hody Jones é o Capitão dos Novos Piratas Homens-Peixe." },
  { correto: true,  texto: "Hody Jones e seus companheiros não possuem recompensa." },
  { correto: true,  texto: "Houve um Crossover entre One Piece e Dragon Ball Z no anime." },
  { correto: true,  texto: "Impel Down tem 6 níveis." },
  { correto: true,  texto: "Issho é um Almirante da Marinha." },
  { correto: true,  texto: "Issho nasceu na Grand Line." },
  { correto: true,  texto: "Issho comeu a Zushi Zushi no Mi, que o permite manipular a gravidade." },
  { correto: true,  texto: "Issho decidiu se cegar porque havia muitas coisas que ele não queria ver." },
  { correto: true,  texto: "Izou nasceu em Wano." },
  { correto: true,  texto: "Jango é um Marinheiro e ex-imediato do Capitão Kuro." },
  { correto: true,  texto: "Jesus Burgess é o Timoneiro dos Piratas do Barba Negra." },
  { correto: true,  texto: "Jinbe é o Timoneiro dos Piratas do Chapéu de Palha." },
  { correto: true,  texto: "Jinbe é oficialmente o décimo membro dos Piratas do Chapéu de Palha." },
  { correto: true,  texto: "Jinbe é um membro dos Piratas do Chapéu de Palha e ex-Shichibukai." },
  { correto: true,  texto: "Joy Boy foi mencionado no Ryugu Poneglyph lido por Nico Robin enquanto ela estava na Floresta do Mar." },
  { correto: true,  texto: "Joy Boy tentou levantar a Noah com a ajuda de Poseidon, mas ele quebrou sua promessa com a ilha dos Tritões." },
  { correto: true,  texto: "Kalgara foi revelado como um usuário de Haki da Observação." },
  { correto: true,  texto: "Kenbushoku no Haki garante ao usuário o sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas." },
  { correto: true,  texto: "Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Kid." },
  { correto: true,  texto: "Killer é um pirata do South Blue e membro do Kid Pirates" },
  { correto: true,  texto: "Kinemon comeu a Fuku Fuku no Mi." },
  { correto: true,  texto: "Kin'emon comeu a Fuku Fuku no Mi." },
  { correto: true,  texto: "Kinemon é usuário de Haki da Observação e do Armamento." },
  { correto: true,  texto: "Kinemon pode se comunicar através de peidos, fazendo eles soarem como a linguagem humana." },
  { correto: true,  texto: "Kizaru comeu a Pika Pika no Mi." },
  { correto: true,  texto: "Koala é uma Humana que pode usar o Karate Tritão." },
  { correto: true,  texto: "Koala é uma Oficial do Exército Revolucionário." },
  { correto: true,  texto: "Koala era um membro dos Piratas do Sol." },
  { correto: true,  texto: "Koala está lutando no Exército Revolucionário para mudar o mundo de uma forma que os Trtões e as Sereias sejam tratados como pessoas normais." },
  { correto: true,  texto: "Kuma é conhecido como Tirano." },
  { correto: true,  texto: "Kureha nasceu em Drum Island." },
  { correto: true,  texto: "Kuro, também conhecido pelo seu apelido Klahadore, é o capitão dos Piratas Black Cat." },
  { correto: true,  texto: "Kuroobi é um oficial dos Piratas do Arlong e ex-membro dos Piratas do Sol." },
  { correto: true,  texto: "Kuzan nasceu no South Blue." },
  { correto: true,  texto: "Laboon é Macho." },
  { correto: true,  texto: "Laffitte cresceu no West Blue, onde se tornou xerife." },
  { correto: true,  texto: "Laffitte nasceu no West Blue." },
  { correto: true,  texto: "Lucky Roo foi um dos primeiros membros a entrar na tripulação do Shanks após ele formar os Piratas do Ruivo." },
  { correto: true,  texto: "Lucky Roo é um membro dos Piratas do Ruivo." },
  { correto: true,  texto: "Lucky Roo foi quem originalmente conseguiu a Gomu Gomu no Mi de um navio pirata inimigo." },
  { correto: true,  texto: "Lucky Roo nasceu no South Blue." },
  { correto: true,  texto: "Lucky Roo pode parecer gordo e lento, mas na verdade ele é um lutador muito ágil e rapido." },
  { correto: true,  texto: "Luffy realmente nasceu em Foosha." },
  { correto: true,  texto: "Luffy tem uma fruta do diabo do tipo Paramecia." },
  { correto: true,  texto: "Machvise comeu a Ton Ton no Mi." },
  { correto: true,  texto: "Magellan nasceu na Grand Line." },
  { correto: true,  texto: "Marco comeu a Tori Tori no Mi, tipo Fênix, uma Zoan Mítica." },
  { correto: true,  texto: "Marco nasceu na Grand Line." },
  { correto: true,  texto: "Masira e Shoujo têm uma recompensa de 23,000,000 e 36,000,000 de berry, respectivamente." },
  { correto: true,  texto: "Masira nasceu no North Blue." },
  { correto: true,  texto: "Mihawk tornou-se famoso antes da Grande Era dos Piratas sequer começar." },
  { correto: true,  texto: "Miss Doublefinger nasceu na Grand Line." },
  { correto: true,  texto: "Miss Goldenweek fez dupla com o Mr.3 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas." },
  { correto: true,  texto: "Miss Goldenweek não comeu uma fruta do diabo." },
  { correto: true,  texto: "Miss Goldenweek nasceu no North Blue." },
  { correto: true,  texto: "Miss Valentine nasceu no West Blue" },
  { correto: true,  texto: "Mohji é um pirata e o imediato dos Piratas do Buggy,bem como um membro da Aliança do Buggy e Alvida." },
  { correto: true,  texto: "Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Caribou." },
  { correto: true,  texto: "Momoo desenvolveu um trauma a respeito do Luffy e do Sanji, sofrendo um ataque de pânico só de vê-los." },
  { correto: true,  texto: "Momoo é macho." },
  { correto: true,  texto: "Monet e Sugar são irmãs." },
  { correto: true,  texto: "Monkey D. Garp nasceu no East Blue." },
  { correto: true,  texto: "Monkey D. Luffy nasceu em Foosha Village." },
  { correto: true,  texto: "Mr. 2 tem o mesmo dublador do Franky e do Jango." },
  { correto: true,  texto: "Mr. 1 comeu a Supa Supa no Mi." },
  { correto: true,  texto: "Mr. 3 agora é reconhecido como um executivo dos Piratas do Buggy." },
  { correto: true,  texto: "Mr. 4 nasceu na Grand Line." },
  { correto: true,  texto: "Mr. 5 nasceu no South Blue." },
  { correto: true,  texto: "Mr. 5 pode comer coisas explosivas e sua comida favorita é pólvora." },
  { correto: true,  texto: "Mr. 9 nasceu no West Blue." },
  { correto: true,  texto: "Neptune é um personagem do One Piece." },
  { correto: true,  texto: "Nico Robin é conhecida como a Criança Demônio." },
  { correto: true,  texto: "Nico Robin é referida como \"Luz da Revolução\" pelo Exército Revolucionário." },
  { correto: true,  texto: "Nico Robin também é conhecida como Miss Allsunday." },
  { correto: true,  texto: "O aniversário da Miss Merry Christmas é no natal, por razões óbvias." },
  { correto: true,  texto: "O aniversário da Miss Valentine é no Valentines Day, por razões óbvias." },
  { correto: true,  texto: "O cabelo do Trebol é preto." },
  { correto: true,  texto: "O Canhão do Mr. 4 comeu uma Fruta do Diabo e tornou-se um cachorro." },
  { correto: true,  texto: "O dragão contra qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por Vegapunk em um labortório em Punk Hazard." },
  { correto: true,  texto: "O navio que a Hancock e as piratas Kuja navegam é chamado de Perfume Snake." },
  { correto: true,  texto: "O nome da espada do Shanks é Gryphon." },
  { correto: true,  texto: "O nome do navio do Mr. 2 era Swanda Express." },
  { correto: true,  texto: "O nome do Navio que Mr. 5 e Miss Valentine usavam em suas operações era Pop Rock Candy." },
  { correto: true,  texto: "O nome do navio que o Mr. 1 e a Miss Doublefinger usavam em suas operaçòes era Kill Sasssoon." },
  { correto: true,  texto: "O nome do navio que os Piratas Donquixote usaram nos dias deles no North Blue era Numancia Flamingo." },
  { correto: true,  texto: "O nome dos navios do Masira e do Shoujo é Victory Hunter e Utan Sonar, respectivamente." },
  { correto: true,  texto: "O nome verdadeiro da Miss Goldenweek é Marianne." },
  { correto: true,  texto: "O nome verdadeiro da Miss Merrychristmas é Drophy." },
  { correto: true,  texto: "O nome verdadeiro do Barba Marrom é Chadros Higelyges." },
  { correto: true,  texto: "O nome verdadeiro do Hatchan é Hatchan." },
  { correto: true,  texto: "O nome verdadeiro do Mr. 4 é Babe, provavelmente em referência ao famoso jogador de basebol Babe Ruth." },
  { correto: true,  texto: "O nome verdadeiro do Mr. 5 é Gem." },
  { correto: true,  texto: "O primeiro beijo conhecido de Sanji foi com a Pudding." },
  { correto: true,  texto: "O principal navio do Exército Revolucionário é chamado de Viento GRANMA." },
  { correto: true,  texto: "O Red Hawk do Luffy é uma homenagem ao Hiken do Ace." },
  { correto: true,  texto: "O sonho de Crocodile era se tornar o Rei dos Piratas." },
  { correto: true,  texto: "O verdadeiro nome da Miss Doublefinger é Zala." },
  { correto: true,  texto: "O verdadeiro nome da Miss Valentine é Mikita." },
  { correto: true,  texto: "O verdadeiro nome do Mr. 1 é Daz Bones." },
  { correto: true,  texto: "O verdadeiro nome do Mr. 2 é Bon Clay Bentham." },
  { correto: true,  texto: "O verdadeiro nome do Mr. 3 é Galdinho." },
  { correto: true,  texto: "Oars é um gigante." },
  { correto: true,  texto: "Objetos podem comer Frutas do Diablo." },
  { correto: true,  texto: "Os Unluckies nasceram na Grand Line." },
  { correto: true,  texto: "Os Yeti Cool Brothers são parte de uma subespécie desconhecida de gigantes." },
  { correto: true,  texto: "Otohime era conhecida pela alcunha \"Encarnação do Amor\" devido a sua incrível bondade e busca pela paz entre diferentes espécies." },
  { correto: true,  texto: "Otohime tinha um Haki da Observação muito desenvolvido, o que a permitia entender profundamente a emoção dos outros." },
  { correto: true,  texto: "Pagaya é pai da Conis." },
  { correto: true,  texto: "Pappag é uma estrela do mar que é mascote da Camie e também professor. Ele é o criador de uma linha de moda" },
  { correto: true,  texto: "Pearl é o comandante da segunda unidade dos Piratas do Krieg." },
  { correto: true,  texto: "Pekoms comeu a Kame Kame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante." },
  { correto: true,  texto: "Pekoms tem uma Fruta do Diabo do tipo Zoan." },
  { correto: true,  texto: "Pekoms tem uma impressionante recompensa de 330,000,000 de berry." },
  { correto: true,  texto: "Pell nasceu em Alabasta." },
  { correto: true,  texto: "Pica tem uma Fruta do Diabo do tipo Paramecia." },
  { correto: true,  texto: "Por causa de seus crimes Sanjuan Wolf foi aprisionado em uma grande cela no nível 6 de Impel Down." },
  { correto: true,  texto: "Portgas D. Ace é filho da Rouge." },
  { correto: true,  texto: "Portgas D. Ace é filho do Gold Roger." },
  { correto: true,  texto: "Portgas D. Ace era o comandante da segunda divisão dos Piratas do Barba Branca." },
  { correto: true,  texto: "Portgas D. Ace era o segundo comandante da divisão dos Piratas do Barba Branca." },
  { correto: true,  texto: "Portgas D. Ace era um usuário de Haki do Rei." },
  { correto: true,  texto: "Portgas D. Ace nasceu em Baterilla." },
  { correto: true,  texto: "Poseidon é uma das armas antigas." },
  { correto: true,  texto: "Rebecca pode usar o Kenbunshoku no Haki." },
  { correto: true,  texto: "Rob Lucci enfrentou Sabo depois do Timeskip." },
  { correto: true,  texto: "Rob Lucci nasceu na Grand Line." },
  { correto: true,  texto: "Robin foi o sétimo membro a entrar na tripulação dos Chapéu de Palha." },
  { correto: true,  texto: "Rosinante comeu a Nagi Nagi no Mi." },
  { correto: true,  texto: "Sabo comeu a Mera Mera no Mi." },
  { correto: true,  texto: "Sadi nasceu na Grand Line." },
  { correto: true,  texto: "Salome é uma serpente fêmea." },
  { correto: true,  texto: "Sanji em sua infância tem a mesma dubladora que o Chopper." },
  { correto: true,  texto: "Sanji nasceu no North Blue." },
  { correto: true,  texto: "Sanjuan Wolf é o capitão do sétimo navio, liderando a sétima frota do Teach." },
  { correto: true,  texto: "Sanjuan Wolf nasceu em West Blue." },
  { correto: true,  texto: "Sanjuan Wolf tem uma fruta do diabo que o permite aumentar o próprio tamanho." },
  { correto: true,  texto: "Scratchmen Apoo é da Tribo Longarm , um infâme pirata com tema de música e capitão dos Piratas On Air." },
  { correto: true,  texto: "Scratchmen Apoo é um infâme pirata com tema de música, membro da tribo Braço-Longo e capitão dos Piratas On Air." },
  { correto: true,  texto: "Sengoku nasceu no South Blue." },
  { correto: true,  texto: "Shakky ajudou a abrigar as Gorgon Sisters depois que elas escaparam dos Nobres Mundiais junto com Gloriosa e Rayleigh." },
  { correto: true,  texto: "Shanks é um membro dos Yonkou que governa o Novo Mundo e capitão dos Piratas do Ruivo." },
  { correto: true,  texto: "Shanks nasceu no West Blue." },
  { correto: true,  texto: "Shanks tem uma cicatriz no olho esquerdo." },
  { correto: true,  texto: "Shiliew é o capitão da segunda frota do Teach." },
  { correto: true,  texto: "Shiryu é o capitão da segunda frota do Teach." },
  { correto: true,  texto: "Shiryu nasceu na Grand Line." },
  { correto: true,  texto: "Silvers Rayleigh tem uma esposa no Arquipélago Sabaody." },
  { correto: true,  texto: "Smoker comeu a Moku Moku no Mi." },
  { correto: true,  texto: "Smoker é usuário do Haki do Armamento e da Observação." },
  { correto: true,  texto: "Sogeking na verdade é o Usopp." },
  { correto: true,  texto: "Stussy nasceu na Grand Line." },
  { correto: true,  texto: "Sugar ficou permanentemente traumatizada com o rosto do Usopp, tornando-se um trauma incurável." },
  { correto: true,  texto: "Tamago comeu a Tama Tama no Mi, que o permite ciclar entre diferentes formas." },
  { correto: true,  texto: "Tamago é membro da tribo dos Pernas Longas." },
  { correto: true,  texto: "Tamago perdeu o olho esquerdo para Pedro." },
  { correto: true,  texto: "Tashigi nasceu no East Blue." },
  { correto: true,  texto: "Teach foi o responsável por cicatrizar o olho de Shanks com sua arma de garras." },
  { correto: true,  texto: "Ton Ton no Mi é uma versão superior da Kilo Kilo no Mi." },
  { correto: true,  texto: "Trafalgar Law comeu a Ope Ope no Mi." },
  { correto: true,  texto: "Trafalgar Law é o capitão e doutor dos Heart Pirates." },
  { correto: true,  texto: "Trafalgar Law nomeou sua tripulação por causa do Corazón, como homenagem ao seu nome e porque ele mudou seu coração para melhor." },
  { correto: true,  texto: "Trafalgar Law perdeu um braço no Arco de Dressrosa." },
  { correto: true,  texto: "Tralfagar Law é conhecido por ser o Cirurgião da Morte." },
  { correto: true,  texto: "Trebol é usuário do Haki da Observação e do Armamento." },
  { correto: true,  texto: "Trebol foi o primeiro a encontrar a Ito Ito no Mi quando era um criminoso." },
  { correto: true,  texto: "Tsuru comeu a Woshu Woshu no Mi." },
  { correto: true,  texto: "Tsuru nasceu no North Blue." },
  { correto: true,  texto: "Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitão dos Piratas Fallen Monk." },
  { correto: true,  texto: "Usopp foi o terceiro membro a entrar na tripluação dos Chapéu de Palha." },
  { correto: true,  texto: "Van Augur nasceu no East Blue." },
  { correto: true,  texto: "Van Augur, o Supersônico, é um Sniper dos Piratas do Barba Negra e um excelente atirador." },
  { correto: true,  texto: "Vasco Shot é o capitão da oitavo navio, liderando a oitava frota do Teach." },
  { correto: true,  texto: "Vergo conhece o Doflamingo desde quando ele era uma criança." },
  { correto: true,  texto: "Vergo foi o primeiro Corazón." },
  { correto: true,  texto: "Wapol é o primeiro rei mostrado na série." },
  { correto: true,  texto: "Yasopp nasceu no East Blue, em Syrup Village." },
  { correto: true,  texto: "Zeff perdeu sua perna direita para salvar Sanji." },
  { correto: true,  texto: "Zephyr é o único Almirante que não comeu uma Fruta do Diabo." },
  { correto: true,  texto: "Zephyr é um personagem non-canon." },
  { correto: true,  texto: "Zeus é um personagem de One Pece." },
  { correto: true,  texto: "Zoro empunhou mais de 8 espadas diferentes no anime." },
  { correto: true,  texto: "[GLA] Você só pode trocar seus equipamentos em uma Zona Segura." },
  { correto: true,  texto: "[GLA] Em Conomi Island você pode encontrar os seguintes inimigos: Moles, Wolves e Baby Moles." },

  // ── FALSO ─────────────────────────────────────────────────────────────────────
  { correto: false, texto: "[GLA] A habilidade Liberation, do Marshall D. Teach, tem dois segundos de tempo de recarga e 10 de poder" },
  { correto: false, texto: "[GLA] A habilidade da Robin, Spider Net, pode ser destruída por alguns ataques." },
  { correto: false, texto: "[GLA] A habilidade de nível 100 do Arlong, Shark on Tank, imobiliza o inimigo." },
  { correto: false, texto: "[GLA] A habilidade Motivation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque." },
  { correto: false, texto: "[GLA] A rotação semanal muda todo sábado." },
  { correto: false, texto: "[GLA] Alvida, Don Krieg, Gin e Pearl são os únicos boss de missão especial que não aparecem nos spawns das ilhas." },
  { correto: false, texto: "[GLA] Alvida Pirates é a única Missão Especial do modo história sem uma versão no modo Difícil." },
  { correto: false, texto: "[GLA] Anel da cruz é um item recomendado para o nível 50." },
  { correto: false, texto: "[GLA] Atualmente existem somente 10 personagens Bronze disponíveis." },
  { correto: false, texto: "[GLA] Atualmente Pearl é o único personagem com três classes-Tanque,Especialista e Lutador." },
  { correto: false, texto: "[GLA] Atum e a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70." },
  { correto: false, texto: "[GLA] Backflips e habilidades de evasão concedem imunidade a dano e imobilizações." },
  { correto: false, texto: "[GLA] Baratie e recomendado para jogadores do level 42 a 50 no minimapa do jogo." },
  { correto: false, texto: "[GLA] Basil Hawkins pode usar sua passiva chamada The Magician para trocar de lugar com seus fantoches." },
  { correto: false, texto: "[GLA] Bastão do Rei Macaco é um item que pode ser usado apenas por lutadores." },
  { correto: false, texto: "[GLA] Buchi pode usar a habilidade Take the Lead para chamar Sham para lutar ao lado dele." },
  { correto: false, texto: "[GLA] Calça de Tritão é o item mais caro que o Genzo vende e custa 10000 berry." },
  { correto: false, texto: "[GLA] Capone Gang Bege e seus aliados ficam imunes dentro do Big Father." },
  { correto: false, texto: "[GLA] Carne de Porco Gourmet é a comida mais demorada para cozinhar do Baratie. Demora 8 minutos." },
  { correto: false, texto: "[GLA] Cerveja Forte é a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70." },
  { correto: false, texto: "[GLA] Cocoyasi Village é recomendado para jogadores do level 48 a 60 no minimapa do jogo." },
  { correto: false, texto: "[GLA] Daddy MCShooty é um inimigo em Loguetown." },
  { correto: false, texto: "[GLA] Dracule Mihawk desacelera seus próprios aliados com a habilidade Taka no Me." },
  { correto: false, texto: "[GLA] É possível cozinhar alguns alimentos na casa da Nojiko." },
  { correto: false, texto: "[GLA] É possível criar Medalhas Dinâmicas de Diamante por 40 Moedas Piratas no Mercado Negro." },
  { correto: false, texto: "[GLA] É possível criar Medalhas Dinâmicas de Ouro por 15 Moedas Piratas no Mercado Negro." },
  { correto: false, texto: "[GLA] É possível criar Medalhas Dinâmicas de Prata por 8 Moedas Piratas no Mercado Negro." },
  { correto: false, texto: "[GLA] É possível criar Poção Média de EXP, Poção Grande de EXP e Poção Pequena de EXP no Mercado Negro." },
  { correto: false, texto: "[GLA] É possível criar Poção Pequena de EXP no Mercado Negro." },
  { correto: false, texto: "[GLA] É preciso completar com um time de especialistas para ganhar a conquista do Arlong." },
  { correto: false, texto: "[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 18." },
  { correto: false, texto: "[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 25." },
  { correto: false, texto: "[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 10." },
  { correto: false, texto: "[GLA] Em regra, emotes são desbloqueados no nível 40." },
  { correto: false, texto: "[GLA] Enquanto está em chamas, Pearl tem as seguintes habilidades - Fire Pearl Shot, Fire Presente, Fire Pearl Close e Fire Pearl Daítokuten." },
  { correto: false, texto: "[GLA] Erros no jogo devem ser reportados no servidor do Discord." },
  { correto: false, texto: "[GLA] Espada Dadao é um item recomendado para o nível 10." },
  { correto: false, texto: "[GLA] Existem 30 conquistas para completar no modo história das missões especiais." },
  { correto: false, texto: "[GLA] Existem Bronze Berry. Silver Berry, Gold Berry e Diamond Berry." },
  { correto: false, texto: "[GLA] Fire Pearl é o nome da passiva do Pearl." },
  { correto: false, texto: "[GLA] Gear Third é a habilidade mais forte do jogo em termos de poder." },
  { correto: false, texto: "[GLA] Genzo vende Bandana de Tritão, Calça de Tritão, Anel do Mar e Turbante do Mar por 5000 berry cada." },
  { correto: false, texto: "[GLA] Há uma Prisioneira chamada Tita no Arlong Park." },
  { correto: false, texto: "[GLA] Helmeppo está localizado no mesmo prédio que seu pai Morgan." },
  { correto: false, texto: "[GLA] Henry Needle, Henry Blazer, Henry Stripe e Henry Ford são nomes de algumas habilidades do Niji." },
  { correto: false, texto: "[GLA] Hideka é a avó do Sora" },
  { correto: false, texto: "[GLA] Island of Rare Animals é recomendada para jogadores do level 38 a 50 no minimapa do jogo." },
  { correto: false, texto: "[GLA] Jango é o único boss de Missão Especial que também é um NPC." },
  { correto: false, texto: "[GLA] Jinbe é o único personagem Diamante com a classe Tanque." },
  { correto: false, texto: "[GLA] Kiribachi é um item que pode ser usado por todas as classes, exceto especialista." },
  { correto: false, texto: "[GLA] Kumo Island é a única ilha sem uma instância do Black Market por perto." },
  { correto: false, texto: "[GLA] Kumo Island é recomendado para jogadores do level 64 a 70 no minimapa do game." },
  { correto: false, texto: "[GLA] Kuro causa 25% a mais de dano quando ataca inimigos pelas costas." },
  { correto: false, texto: "[GLA] Lâmina Escondida é um item que pode ser usado por todas as classes." },
  { correto: false, texto: "[GLA] Leo, discípulo de Carmen, está na biblioteca de Loguetown." },
  { correto: false, texto: "[GLA] Loguetown é recomendada para jogadores do level 56 a 70 no minimapa do jogo." },
  { correto: false, texto: "[GLA] Luffy recebe menos dano dos ataques do Vinsmoke Niji porque seu corpo tem propriedades de borracha." },
  { correto: false, texto: "[GLA] Marshall D. Teach ganha 30% de ataque e perde metade da armadura quando sua passiva é ativada." },
  { correto: false, texto: "[GLA] Meito: Shigure é um item que pode ser usado somente por cortantes." },
  { correto: false, texto: "[GLA] Mellorine é o nome da passiva do Sanji." },
  { correto: false, texto: "[GLA] Mes é a habilidade mais forte do jogo em termos de poder." },
  { correto: false, texto: "[GLA] Monkey D. Luffy pode quebrar paredes com a habilidade Gomu Gomu no Ono." },
  { correto: false, texto: "[GLA] Monkey D. Luffy têm as seguintes classes: Bruiser, Lutador e Tanque." },
  { correto: false, texto: "[GLA] Morgan é o único boss de Missão Especial que também é um NPC." },
  { correto: false, texto: "[GLA] Muggy Dama é a habilidade que o Buggy libera no nível 100." },
  { correto: false, texto: "[GLA] Nami pode criar somente 3 nuvens simultaneamente." },
  { correto: false, texto: "[GLA] Não é possivel entrar na mansão da Kaya." },
  { correto: false, texto: "[GLA] Não há um Marine Announcer em Conomi Island." },
  { correto: false, texto: "[GLA] Nefertari Vivi pode fazer uma dança sexy para motivar seus aliados, aumentando o ataque e a defesa deles por 15 segundos." },
  { correto: false, texto: "[GLA] Nico Robin não pode construir pontes com a habilidade Delphinium." },
  { correto: false, texto: "[GLA] Ninjin, um dos Piratas do Usopp, dá algumas missões em Syrup Village." },
  { correto: false, texto: "[GLA] No tutorial do jogo, o NPC que passa instruções para você é o Woop Slap, o prefeito de Foosha Village." },
  { correto: false, texto: "[GLA] NPC Sora em Samui Island é uma menina." },
  { correto: false, texto: "[GLA] O Barba Negra tem as seguintes classes: Especialista, Bruiser e Atirador. A ultima é porque ele tem um revólver." },
  { correto: false, texto: "[GLA] O Kit de Reparo 1.0 restaura 400 pontos de vida do seu navio por segundo." },
  { correto: false, texto: "[GLA] O Kit de Reparo 1.0 restaura 600 pontos de vida do seu navio por segundo." },
  { correto: false, texto: "[GLA] O Kit de Reparo 2.0 restaura 22.000 pontos de vida do seu navio em 20 segundos." },
  { correto: false, texto: "[GLA] O Kit de Reparo 2.0 restaura 700 pontos de vida do seu navio por segundo." },
  { correto: false, texto: "[GLA] O Kit de Reparo 3.0 restaura 30.000 pontos de vida do seu navio em 20 segundos." },
  { correto: false, texto: "[GLA] O Kit de Reparo 3.0 restaura 1000 pontos de vida do seu navio por segundo." },
  { correto: false, texto: "[GLA] O level necessário para fazer a Quest do Capitão Morgan é 17." },
  { correto: false, texto: "[GLA] O NPC Magra pede por 4 Orelhas e Lobo na missão dele em Foosha Village." },
  { correto: false, texto: "[GLA] O sangramento do Killer pode acumular até 4 vezes usando mais Bloody Cuts ou Kira Nokogiri." },
  { correto: false, texto: "[GLA] Orange Town é recomendada para jogadores do level 20 a 30 no minimapa do jogo." },
  { correto: false, texto: "[GLA] Os Kits de Reparo 1.0, 2.0 e 3.0 são vendidos na loja do Mercado Negro pelos respectivos valores 30, 90 e 180 berry." },
  { correto: false, texto: "[GLA] Para iniciar a Quest do Ripper em Shells Town, você precisa primeiro completar a Quest do Helmeppo." },
  { correto: false, texto: "[GLA] O Pearl é o primeiro inimigo em Pirata Armada." },
  { correto: false, texto: "[GLA] Picareta de Mineração é um item para cortantes e tanques." },
  { correto: false, texto: "[GLA] Piiman, um dos piratas do Usopp, dá algumas missões em Syrup Village." },
  { correto: false, texto: "[GLA] Pufferfish e Sharks são considerados monstros nível 3." },
  { correto: false, texto: "[GLA] Quando Bonney usa sua habilidade Unbridled Power, ela transforma todos a sua em bebês e fica invulnerável por 9 segundos." },
  { correto: false, texto: "[GLA] Quando Sanji cura uma mulher, ele fica motivado e recebe bônus de velocidade e ataque por 10 segundos." },
  { correto: false, texto: "[GLA] Sabo é o nome da criança que a Nojiko pede para ajudar no Arlong Park." },
  { correto: false, texto: "[GLA] Sanji pode se curar com a habildade Master Cook." },
  { correto: false, texto: "[GLA] Sanzen Sekai é a habilidade mais forte do jogo em termos de poder." },
  { correto: false, texto: "[GLA] Sapi é o NPC que vende Atum em Cocoyasi Village." },
  { correto: false, texto: "[GLA] Sayuri, Asuya e Cherry são nomes de NPCs do Baratie." },
  { correto: false, texto: "[GLA] Shanks imobiliza inimigos em volta dele com a habilidade Busoshoku Haki Waves." },
  { correto: false, texto: "[GLA] Shanks mata inimigos fracos instantaneamente com a habilidade Kenbushoku Haki." },
  { correto: false, texto: "[GLA] Slime é um inimigo exclusivo de Loguetown." },
  { correto: false, texto: "[GLA] Snowflakes é o nome do animal de estimação do Sora." },
  { correto: false, texto: "[GLA] Spider e Giant Spider são os únicos inimigos em Kumo Island." },
  { correto: false, texto: "[GLA] Syrup Village é a única ilha com duas entradas de doca no East Blue." },
  { correto: false, texto: "[GLA] Todos os chapéu de Palha possuem uma Skin do Strong World." },
  { correto: false, texto: "[GLA] Trafalgar Law não pode quebrar paredes com a habilidade Injection Shot." },
  { correto: false, texto: "[GLA] Trafalgar Law não pode usar nenhuma habilidade quando está fora da Room." },
  { correto: false, texto: "[GLA] Um personagem Diamante precisa de mais medalhas para ter suas estrelas melhoradas do que um personagem Ouro." },
  { correto: false, texto: "[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 15 gemas e a segunda 20 gemas." },
  { correto: false, texto: "[GLA] Você não pode trocar sua página de equipamentos em uma Zona Segura." },
  { correto: false, texto: "[GLA] Você pode começar uma missão diária de derrotar Slimes na Samui Island." },
  { correto: false, texto: "[GLA] Você pode conseguir o item Colar do Saru em qualquer Missão Difícil do East Blue." },
  { correto: false, texto: "[GLA] Você pode construir uma Caixa de Música por 200 moedas piratas no Mercado Negro." },
  { correto: false, texto: "A recompensa atual do Marshall D. Teach é de 2,247,600,000 de berry." },
  { correto: false, texto: "[GLA] Você pode encontrar 8 entradas para o Mercado Negro no East Blue." },
  { correto: false, texto: "[GLA] Você pode usar a mesa de construção nas docas para transforma 5 Poções Médias de Experiência em 1 Poção Grande de Experiência." },
  { correto: false, texto: "[GLA] Você pode usar a mesa de construção nas docas para transformar 10 Poções Médias de Experiência em 1 Poção Grande de Experiência." },
  { correto: false, texto: "[GLA] Você pode usar a mesa de construção nas docas para transformar 10 Poções Pequenas de Experiência em 2 Poção Média de Experiência." },
  { correto: false, texto: "[GLA] Você precisa alimentar um prisioneiro na Quest da Ririka." },
  { correto: false, texto: "[GLA] Você precisa derrotar 50 cobras na missão do Coby." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de atiradores para completar a conquista dos Piratas do Buggy." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de especialistas para completar a conquista dos Piratas da Alvida." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de especialistas para completar a conquista dos Piratas do Arlong." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de mulheres para completar a conquista dos Black Cat." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de tanques para completar a conquista da Base da Marinha." },
  { correto: false, texto: "[GLA] Você precisa vencer com uma equipe de homens para completar a conquista da Armada Pirata." },
  { correto: false, texto: "[GLA] Uchimizu é uma habilidade que pode ser usada por Jinbe, Chew e Arlong." },
  { correto: false, texto: "A alcunha do Laffitte, shinigami ou deus da morte, vem do fato dele gosta de brincar com a vida das pessoas, assim como um shinigami." },
  { correto: false, texto: "A atual recompensa da Boa Hancock é 79,000,000 de berry." },
  { correto: false, texto: "A atual recompensa de Marshall D. Teach é de 2.247.600 de berries." },
  { correto: false, texto: "A atual recompensa da Nami é de 66,000,000 de berry." },
  { correto: false, texto: "A barreira do Bartolomeo quebrou somente uma vez durante o anime." },
  { correto: false, texto: "A comida favorita da Sugar é laranja." },
  { correto: false, texto: "A comida favorita do Marco é uva." },
  { correto: false, texto: "A comida favorita do Teach é torta de maçã." },
  { correto: false, texto: "A cor do cabelo da Miss Valentine é verde." },
  { correto: false, texto: "A espada de Shilliew é uma Meito chamada \"Rain\"." },
  { correto: false, texto: "A mãe do Usopp nasceu no South Blue." },
  { correto: false, texto: "A maior recompensa conhecida é de 1,500,000,000 de berry." },
  { correto: false, texto: "A maior recompensa conhecida é de 2,257,600,000." },
  { correto: false, texto: "A primeira recompensa da Nico Robin foi de 78,000,000 de berry, a meesma quantia de sua mãe Nico Olvia." },
  { correto: false, texto: "A recompensa da Baby Five é de 17,000,000 de berry." },
  { correto: false, texto: "A recompensa da Baby Five é de 23,000,000 de berry." },
  { correto: false, texto: "A recompensa da Boa Hancock é de 79.000.000 de berries." },
  { correto: false, texto: "A recompensa da Jewelry Bonney é de 140,000,000 de berry." },
  { correto: false, texto: "A recompensa da Miss Valentine é de 7,000,000 de berry." },
  { correto: false, texto: "A recompensa da Olivia era de 79,000,000 de berry, o mesmo que sua filha Nami recebeu depois..." },
  { correto: false, texto: "A recompensa do Lao G era de 60,000,000 de bery antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Machvise era de 10,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Mont Blanc Cricket é desconhecida." },
  { correto: false, texto: "A recompensa do Mr. 2 é de 30,000,000 de berry." },
  { correto: false, texto: "A recompensa do Mr. 4 é de 3,000,000 de berry." },
  { correto: false, texto: "A recompensa do Mr. 5 é de 9,000,00 de berry." },
  { correto: false, texto: "A recompensa do Mr.3 é de 23,000,000 de berry." },
  { correto: false, texto: "A recompensa do Pica era de 100,000,000 de berry antes de ser con gelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Senor Pink era de 56,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Tamago é de 429,500,000 de berry." },
  { correto: false, texto: "A recompensa do Trebol era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Urouge é de 100,000,000 de berry." },
  { correto: false, texto: "A recompensa do X-Drake é de 220,200,000 de berry." },
  { correto: false, texto: "A recompensa do Zeff é de 47,600,000 de berry." },
  { correto: false, texto: "A recompensa do Zoro é maior que a do Sanji." },
  { correto: false, texto: "A recompensa dos Shichibukai pode aumentar." },
  { correto: false, texto: "A Sniper Island está localizada na Grand Line." },
  { correto: false, texto: "A terceira recompensa do Monkey D. Luffy foi de 400,000,000 de berry." },
  { correto: false, texto: "Ace comeu a Mira Mira no Mi." },
  { correto: false, texto: "Aisa nasceu com um Haki do Armamento avançado." },
  { correto: false, texto: "Akainu nasceu na Grand Line." },
  { correto: false, texto: "Akira Toriyama é o criador de One Piece." },
  { correto: false, texto: "Alvida é a antiga capitã dos Piratas do Buggy." },
  { correto: false, texto: "A recompensa de Hathan é de 7.000.000." },
  { correto: false, texto: "A recompensa de um pirata reflete a força dele." },
  { correto: false, texto: "A recompensa do Buffalo é de 13,000,000 de berry." },
  { correto: false, texto: "A recompensa do Buffalo é de 15,000,000 de berry." },
  { correto: false, texto: "A recompensa do Daz Bones é de 70,000,000 de berry." },
  { correto: false, texto: "A recompensa do Dellinger era de 12,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Demaro Black é de 26,300,000 de berry." },
  { correto: false, texto: "A recompensa do Diamante era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai." },
  { correto: false, texto: "A recompensa do Fisher Tiger era de 200,000,000 de berry." },
  { correto: false, texto: "A recompensa do Foxy é de 25,000,000 de berry." },
  { correto: false, texto: "A recompensa do Gin é de 10,000,000 de berry." },
  { correto: false, texto: "A recompensa do Hatchan é de 7,000,000 de berry." },
  { correto: false, texto: "A recompensa do Jinbe é de 439,000,000 de berry." },
  { correto: false, texto: "A recompensa do Jinbe era de 200,000,000 de berry antes dele se tomar um Shichibukai." },
  { correto: false, texto: "A recompensa do Kuro é de 6,000,000 de berry." },
  { correto: false, texto: "A recompensa do Kuroobi é de 8,000,000 de berry." },
  { correto: false, texto: "Antes dos eventos da guerra, Doc Q tinha uma impressionanterecompensa de 72,500,000 de berry." },
  { correto: false, texto: "Antes dos eventos da guerra, Jesus Burgess tinha uma recompensa de 200,000,000 de berry." },
  { correto: false, texto: "Antes dos eventos da guerra, Laffitte tinha uma recompensa de 42,000,000 de berry." },
  { correto: false, texto: "Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 60,000,000 de berry." },
  { correto: false, texto: "Aokiji comeu a Yuki Yuki no Mi." },
  { correto: false, texto: "Após os eventos em Punk Hazard, Smoker se tornou oficialmente o Líder da G-4." },
  { correto: false, texto: "Após ser diagnosticado com sua doença, Gol D. Roger levou dois anos para encontrar o One Piece." },
  { correto: false, texto: "Arlong era capitão dos Piratas do Sol e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy." },
  { correto: false, texto: "Arlong já foi um escravo." },
  { correto: false, texto: "Assim como Kuzan, Smoker deseja acabar com o sistema de Shichibukai." },
  { correto: false, texto: "Atualmente o cabelo do Arlong é Roxo." },
  { correto: false, texto: "Atualmente o Monkey D. Luffy tem a maior recompensa conhecida." },
  { correto: false, texto: "Avalo Pizarro é o capitão do terceiro navio, liderando a terceira frota do Teach." },
  { correto: false, texto: "Avalo Pizarro era originalmente rei de um país no West Blue." },
  { correto: false, texto: "Baby 5 comeu a Boku Boku no Mi." },
  { correto: false, texto: "Baby Five nasceu na Grand Line." },
  { correto: false, texto: "Bacura é um usuário da Fruta do Diabo do tipo Zoan." },
  { correto: false, texto: "Barba Branca comeu a Goro Goro no Mi." },
  { correto: false, texto: "Barba Branca foi o responsável por cicatrizar o olho e Shanks com sua arma de garras." },
  { correto: false, texto: "Barba Branca nasceu na Sphinx Island no North Blue." },
  { correto: false, texto: "Barba Negra é um Almirante dos Piratas do Barba Negra e membro dos Shichibukai." },
  { correto: false, texto: "Barba Negra nasceu no North Blue." },
  { correto: false, texto: "Bartholomew Kuma era conhecido como um Pacifista." },
  { correto: false, texto: "Bartholomew Kuma tinha a Fruta do Diabo do Espelho." },
  { correto: false, texto: "Bartolomeo tem a Fruta do Diabo Nikyu Nikyu no Mi." },
  { correto: false, texto: "Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Mago." },
  { correto: false, texto: "Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no West Blue." },
  { correto: false, texto: "Benn Beckman é o vice-capitão dos Piratas do Shanks." },
  { correto: false, texto: "Benn Beckman não é o personagem mais inteligente que apareceu na saga do East Blue." },
  { correto: false, texto: "Benn Beckman não tem uma recompensa." },
  { correto: false, texto: "Benn Beckman nasceu no East Blue." },
  { correto: false, texto: "Bepo não é um Mink." },
  { correto: false, texto: "Boa Hancock é a capitã das Piratas Kuja e a segunda mulher membro dos Shichibukai." },
  { correto: false, texto: "Boa Hancock nasceu no North Blue." },
  { correto: false, texto: "Boa Hancock tem a mesma dubladora da Reiju." },
  { correto: false, texto: "Boa Marigold e Boa Sandersonia tem somente Haki do armamento." },
  { correto: false, texto: "Boodle é o prefeito de Syrup Village." },
  { correto: false, texto: "Brook está morto há 50 anos." },
  { correto: false, texto: "Brook foi o último membro a entrar na tripulação dos Chapéu de Palha." },
  { correto: false, texto: "Buffalo nasceu na Grand Line." },
  { correto: false, texto: "Buggy é capitão do Clown Pirates e também colíder da Aliança do Buggy e Alvida." },
  { correto: false, texto: "Buggy e Shanks estão na mesma tripulação." },
  { correto: false, texto: "Busoshoku no Haki garante ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas." },
  { correto: false, texto: "Cada um dos principais membros da tripulação do Shanks são do mesmo oceano." },
  { correto: false, texto: "Caesar comeu a Shiro Shiro no Mi." },
  { correto: false, texto: "Capone Gang Bege é capitão do Castle Tank Pirates e também um dos doze piratas classificados como a Pior Geração." },
  { correto: false, texto: "Caribou nasceu no West Blue." },
  { correto: false, texto: "Catarina Devon caça qualquer homem que ela acha atraente e decapita a cabeça deles para adicioná-las na sua coleção pessoal." },
  { correto: false, texto: "Catarina Devon é a capitã do quinto navio, liderando a quinta frota do Teach." },
  { correto: false, texto: "Catarina Devon nasceu na Grand Line." },
  { correto: false, texto: "Charlotte Linlin é uma das filhas da Big Mom." },
  { correto: false, texto: "Charlotte Shujan é um dos filhos da Big Mom." },
  { correto: false, texto: "Chess nasceu no West Blue." },
  { correto: false, texto: "Chopper é um Guaxinim que comeu a Fruta Human-Human." },
  { correto: false, texto: "Como um dos principais membrs do Exército Revolucionário, Koala tem uma recompensa de 320,000,000 de berry." },
  { correto: false, texto: "Crocodile estava atrás da Uranus, uma das armas antigas." },
  { correto: false, texto: "Crocodile foi o segundo oponente a derrotar Luffy em uma batalha." },
  { correto: false, texto: "Crocodile nasceu no North Blue." },
  { correto: false, texto: "Damaro Black, Manjaro, Chocolat, Drip, Turco, Cocoa, MountMOUNTAIN e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos Chapéus de Palha." },
  { correto: false, texto: "Demaro Black, capitão dos Falsos Chapéu de Palha, nasceu no West Blue." },
  { correto: false, texto: "Dentre a Tripulação dos Chapéu de Palha, Luffy é o membro favorito de Eiichiro Oda." },
  { correto: false, texto: "Depois do Timeskip o Franky é o mais alto dos Piratas do Chapéu de Pala." },
  { correto: false, texto: "Diamante foi o primeiro a encontrar Ito Ito no Mi quando era um criminoso." },
  { correto: false, texto: "Diamond Jozu comeu a Mira Mira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável." },
  { correto: false, texto: "Diamond Jozu nasceu na Grand Line." },
  { correto: false, texto: "Doc Q carrega uma grande lança como arma." },
  { correto: false, texto: "Doc Q é o médico dos Piratas do Barba Branca." },
  { correto: false, texto: "Doflamingo e Baby Five tiveram uma complexa relação amorosa." },
  { correto: false, texto: "Doflamingo é usuário de Haki do Armamento e do Rei apenas." },
  { correto: false, texto: "Doflamingo foi o primeiro personagem a desperta sua Fruta do Diabo." },
  { correto: false, texto: "Doflamingo matou Gecko Moria." },
  { correto: false, texto: "Donquixote Doflamingo é o capitão dos Piratas Donquixote." },
  { correto: false, texto: "Dororo é um personagem de One Piece." },
  { correto: false, texto: "Doutor Hiriluk nasceu em Drum Island." },
  { correto: false, texto: "Dracule Mihawk é um membro dos Piratas do Ruivo." },
  { correto: false, texto: "Dracule Mihawk é um Shichibukai e membro dos Piratas do Ruivo." },
  { correto: false, texto: "Dracule Mihawk teve apenas um dublador durante todo o anime." },
  { correto: false, texto: "Duval é irmão do Sanji." },
  { correto: false, texto: "Em termos simples, Haki é a habilidade de sentir energia espiritual (Busoshoku), usar força vital (Haoshoku) e dominar inimigos (Kenbunshoku)." },
  { correto: false, texto: "Emporio Ivankov nasceu no West Blue." },
  { correto: false, texto: "Enel comeu a Gura Gura no Mi." },
  { correto: false, texto: "Enel e seus sacerdotes conquistaram a Lua." },
  { correto: false, texto: "Enel está em Marte." },
  { correto: false, texto: "Eric é um Pirata non-canon que foi mostrado no anime." },
  { correto: false, texto: "Erik e um personagem non-canon de One Piece." },
  { correto: false, texto: "Eustass Kid perdeu seu braço direito." },
  { correto: false, texto: "Existem três tipos de Haki disponíveis para todo mundo." },
  { correto: false, texto: "Foi confirmado que Usopp despertou o Haki da Observação durante o Arco de Punk Hazard." },
  { correto: false, texto: "Foxy comeu a Soro Soro no Mi." },
  { correto: false, texto: "Foxy nasceu no East Blue." },
  { correto: false, texto: "Franky destruiu o projeto da Uranus." },
  { correto: false, texto: "Franky é um robô." },
  { correto: false, texto: "Franky era o antigo líder da Família Franky e atual Capitão dos Piratas Ciborgues." },
  { correto: false, texto: "Franky era originalmente líder da Família Franky e agora é capitão dos Cyborg Pirates." },
  { correto: false, texto: "Franky foi o primeiro ciborgue a aparecer na série." },
  { correto: false, texto: "Franky foi o sétimo membro a entrar na tripulação dos Chapéu de Palha." },
  { correto: false, texto: "Frost é um personagem do One Piece." },
  { correto: false, texto: "Funkfreed é o nome do Elefante do Spandam." },
  { correto: false, texto: "Genzo nasceu no North Blue." },
  { correto: false, texto: "Genzo também é um Médico." },
  { correto: false, texto: "Gin é capitão dos Piratas do Gin." },
  { correto: false, texto: "Gin tem o mesmo dublador do Kuro." },
  { correto: false, texto: "Gin tem uma recompensa de 10,000,000." },
  { correto: false, texto: "Gol D. Roger usava um chapéu similar ao do Luffy." },
  { correto: false, texto: "Golden Lion Shiki é um personagem non-canon." },
  { correto: false, texto: "Gura Gura no Mi é uma Fruta do Diabo do tipo Logia." },
  { correto: false, texto: "Hancock é a Imperatriz do Amazon Lily, motivo pelo qual ela é chamada de Imperatriz Shichibukai." },
  { correto: false, texto: "Haoshoku no Haki concede ao usuario um sextro sentido do mundo ao seu redor e habilidades precognitivas limitadas." },
  { correto: false, texto: "Haoshoku no Haki garante ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas." },
  { correto: false, texto: "Hatchan é um ex-oficial dos Piratas do Sol e membro dos Piratas do Arlong antes de disso." },
  { correto: false, texto: "Hatchan tem 8 braços." },
  { correto: false, texto: "Hody Jones é o Capitão dos Piratas Homens-Peixe." },
  { correto: false, texto: "Impel Down tem 7 níveis." },
  { correto: false, texto: "Inazuma nasceu no North Blue." },
  { correto: false, texto: "Ishoo nasceu no South Blue." },
  { correto: false, texto: "Issho comeu a Fuji Fuji no Mi, que o permite manipular a gravidade." },
  { correto: false, texto: "Issho nasceu no South Blue." },
  { correto: false, texto: "Jango é um Marinheiro e ex-capitâo dos Piratas Black Cack." },
  { correto: false, texto: "Jesus Burgess é navegador dos Piratas do Barba Negra." },
  { correto: false, texto: "Jinbe é o Navegador dos Piratas do Chapéu de Palha." },
  { correto: false, texto: "Jinbe foi o nono membro a entrar na tripulação dos Chapéus de Palha." },
  { correto: false, texto: "Johnny e Yosaku nasceram no West Blue." },
  { correto: false, texto: "Kalgara foi revelado como um usuário de Haki do Armamento." },
  { correto: false, texto: "Kanjuro comeu a Draw Draw no Mi, que o permite trazer a vida tudo o que ele desenha." },
  { correto: false, texto: "Katakuri pode ver 5 minutos no futuro." },
  { correto: false, texto: "Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Killer." },
  { correto: false, texto: "Kid e Killer são irmãos. Juntos, formaram os Piratas do Kid." },
  { correto: false, texto: "Killer é um Pirata do North Blue e membro do Kid Pirates." },
  { correto: false, texto: "Killer perdeu um braço no Timeskip." },
  { correto: false, texto: "Kinemon comeu a Tuku Tuku no Mi." },
  { correto: false, texto: "Kinemon é usuário de Haki do Armamento apenas." },
  { correto: false, texto: "Kizaru nasceu na Grand Line." },
  { correto: false, texto: "Kuro, também conhecido pelo seu apelido Klahadore, é o capitão dos Piratas Neko." },
  { correto: false, texto: "Kuro, Capitão dos Piratas Black Cat, era também conhecido por seu apelido de Klahadore." },
  { correto: false, texto: "Kuroobi é um oficial dos Piratas do Sol e ex-membros dos Piratas do Arlong." },
  { correto: false, texto: "Kuzan decidiu se cegar porque havia muitas coisas que ele não queria ver." },
  { correto: false, texto: "Lucky Roo nasceu no North Blue." },
  { correto: false, texto: "Luffy derrotou Sabo em um duelo durante a infância." },
  { correto: false, texto: "Luffy ganhou sua cicatriz por causa de um tigre em Foosha Village." },
  { correto: false, texto: "Luffy tem uma fruta do Diabo do tipo Logia que tornou seu corpo de borracha." },
  { correto: false, texto: "Machvise comeu a Hon Hon no Mi." },
  { correto: false, texto: "Madame Shyarly é a irmã do Hatchan." },
  { correto: false, texto: "Madame Shyarly é uma das irmãs do Arlong." },
  { correto: false, texto: "Magellan comeu a Moku Moku no Mi." },
  { correto: false, texto: "Marco comeu a Pori Pori no Mi, tipo Fênix, uma Zoan Mítica." },
  { correto: false, texto: "Marco era o comandante da Segunda Divisão e mão direita do Barba Branca." },
  { correto: false, texto: "Masashi Kishimoto é o criador do One Piece." },
  { correto: false, texto: "Masira e Shoujo são irmãos." },
  { correto: false, texto: "Masira e Shoujo têm uma recompensa de 23,000,000 e 26,000,000 de berry, respectivamente." },
  { correto: false, texto: "Masira e Shoujo têm uma recompensa de 36,000,000 e 23,000,000 de berry, respectivamente." },
  { correto: false, texto: "Mihawk não é o único com uma recompensa desconhecida entre os Shichibukai." },
  { correto: false, texto: "Miss Doublefinger nasceu no South Blue." },
  { correto: false, texto: "Miss Goldenweek fez dupla com o Mr. 2 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas." },
  { correto: false, texto: "Miss Goldenweek fez dupla com o Mr.2 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas." },
  { correto: false, texto: "Miss Goldenweek nasceu no west Blue." },
  { correto: false, texto: "Miss Valentine nasceu na Grand Line." },
  { correto: false, texto: "Mohji é um pirata e capitão dos Piratas Leões." },
  { correto: false, texto: "Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Arlong." },
  { correto: false, texto: "Momoo desenvolveu um trauma a respeito do Luffy e do Zoro, sofrendo um ataque de pânico só de vê-los." },
  { correto: false, texto: "Momoo é fêmea." },
  { correto: false, texto: "Monet comeu a Hie Hie no Mi." },
  { correto: false, texto: "Monet tinha uma Fruta do Diabo do tipo Paramercia." },
  { correto: false, texto: "Monkey D. Garp é o verdadeiro pai de Luffy." },
  { correto: false, texto: "Monkey D. Garp nasceu no South Blue." },
  { correto: false, texto: "Monkey D. Luffy foi a primeira pessoa a escapar de Impel Down." },
  { correto: false, texto: "Monkey D. Luffy foi a única pessoa a escapar de Impel Down na história." },
  { correto: false, texto: "Monkey D. Luffy nasceu em Nanko Village," },
  { correto: false, texto: "Mr. 3 queria trair o Crocodile desde o início do arco." },
  { correto: false, texto: "Mr. 4 nasceu no East Blue." },
  { correto: false, texto: "Mr. 5 nasceu no West Blue." },
  { correto: false, texto: "Nami conseguiu o Clima-Tact em Drum Island." },
  { correto: false, texto: "Nami foi o terceiro membro a entrar na tripulação dos Chapéu de Palha." },
  { correto: false, texto: "Nanashaku Jitte é um item de nível 70 que pode ser usado por todas as classes." },
  { correto: false, texto: "Nefertati Vivi é um membro dos Piratas do Chapéu de Palha." },
  { correto: false, texto: "Nico Robin é referida como Demônio da Revolução pelo Exérito Revolucionário." },
  { correto: false, texto: "O anime One Piece é o maior já feito." },
  { correto: false, texto: "O cabelo do Charlotte Cracker é verde." },
  { correto: false, texto: "O dragão contra qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por Caesar em um laboratório em Punk Hazard." },
  { correto: false, texto: "O Exército Revolucionário foi fundado após o nascimento do Luffy." },
  { correto: false, texto: "O gênero de Surume é feminino." },
  { correto: false, texto: "O navio que a Hancock e as Piratas Kuja navegam é chamado de Aroma Snake." },
  { correto: false, texto: "O nome da espada do Shanks é Python." },
  { correto: false, texto: "O nome do navio que o Mr. 1 e a Miss Doublefinger usavam em suas operações era  Kill Season." },
  { correto: false, texto: "O nome do navio que o Mr.5 e a Miss Valentine usavam em suas operações era Bomb Rock Candy." },
  { correto: false, texto: "O nome do navio que os Piratas Donquixote usaram nos dias deles no North Blue era Flamingo Family." },
  { correto: false, texto: "O nome dos navios do Masira e do Shoujo é Utan Sonar e Victory Hunter, respectivamente." },
  { correto: false, texto: "O nome verdadeiro da Baby Five é Babi." },
  { correto: false, texto: "O nome verdadeiro da Miss Goldenweek é Drophy." },
  { correto: false, texto: "O nome verdadeiro da Miss MerryChristmas é Marianne." },
  { correto: false, texto: "O nome verdadeiro do Hatchan é Hatchi." },
  { correto: false, texto: "O nome verdadeiro do Mr. 4 é Derek, provavelmente em referência ao famoso jogador de basebol Derek Jeter." },
  { correto: false, texto: "O nome verdadeiro do Mr. 5 é Rem." },
  { correto: false, texto: "O nome verdadeiro de Trebol é John Trebol." },
  { correto: false, texto: "O primeiro beijo conhecido do Sanji foi com a Violet." },
  { correto: false, texto: "O principal navio do Exército Revolucionário é chamado de Viento GRANMAR." },
  { correto: false, texto: "O projeto da Pluton ainda não foi descoberto." },
  { correto: false, texto: "O verdadeiro nome da Miss Doublefinger é Paula." },
  { correto: false, texto: "O verdadeiro nome do Mr. 3 é Baldino." },
  { correto: false, texto: "O Yonkou Shanks é conhecido por ser o Capitão dos Piratas do Shanks." },
  { correto: false, texto: "Oars é um meio-gigante." },
  { correto: false, texto: "Os Smiles eram feitos pelo Donquixote Doflamingo." },
  { correto: false, texto: "Os Yeti Cool Brothers são parte de uma subespécie de humanos." },
  { correto: false, texto: "Otohime era conhecida pela alcunha \"Reencarnação do amor\" devido a sua incrível bondade e busca pela paz entre diferentes espécies." },
  { correto: false, texto: "Otohime tinha um Haki da Observação e do Armamento muito desenvolvido, o que a permitia entender profundamente a emoção dos outros." },
  { correto: false, texto: "Pagaya é uma estrela do mar que é mascote de Camie e Também professor. Ele é o criador de uma linha de moda." },
  { correto: false, texto: "Pandaman é da tripulação do Law." },
  { correto: false, texto: "Pandaman está na tripulação do Trafalgar Law." },
  { correto: false, texto: "Pappag é um caçador de recompensas que apareceu no Arquipélago Sabaody." },
  { correto: false, texto: "Pearl é o comandante da segunda unidade dos Piratas da Armada Pirata" },
  { correto: false, texto: "Pekoms comeu a Tame Tame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante." },
  { correto: false, texto: "Pekoms tem uma impressionante recompensa de 300,000,000 de berry." },
  { correto: false, texto: "Perona tem o mesmo dublador da Koala." },
  { correto: false, texto: "Pica é usuário do Haki do Armamento apenas." },
  { correto: false, texto: "Portgas D. Ace era o segundo comandante da divisão dos Spades Pirates." },
  { correto: false, texto: "Potgas D. Ace era o comandante da segunda divisão dos Spade Pirates." },
  { correto: false, texto: "Punk Hazard pode ser encontrado com um Log Pose." },
  { correto: false, texto: "Python é o nome da espada do Shanks." },
  { correto: false, texto: "Recompensa do X-Drake é de 220.200.207 berries." },
  { correto: false, texto: "Rob Lucci nasceu no West Blue." },
  { correto: false, texto: "Rosinante comeu a Shiu Shiu no Mi." },
  { correto: false, texto: "Rosinante foi o primeiro Corazón" },
  { correto: false, texto: "Ryuma tinha a sombra de um lendário samurai de Wano." },
  { correto: false, texto: "Sandai Kitetsu (uma das espadas do zoro) enferrujou." },
  { correto: false, texto: "Sanji foi o quinto membro a entrar na tripulação dos Chapéu de Palha." },
  { correto: false, texto: "Sanji nasceu no South Blue." },
  { correto: false, texto: "Sanjuan Wolf é o capitão do quinto navio, liderando a quinta frota do Teach." },
  { correto: false, texto: "Scratchmen Apoo é da tribo Longarm, um infâme pirata com tema de música e capitâo dos Piratas On Music." },
  { correto: false, texto: "Sendai Kitetsu (uma das espadas do Zoro) enferrujou." },
  { correto: false, texto: "Sengoku comeu a Bito Bito no Mi, uma fruta Zoan Mítica." },
  { correto: false, texto: "Sengoku nasceu no North Blue." },
  { correto: false, texto: "Shanks é membro dos Yonko que governam o novo mundo e é o capitão dos piratas do Shanks." },
  { correto: false, texto: "Shanks é um membro dos Yonko que governa o Novo Mundo e capitão dos Piratas do Shanks." },
  { correto: false, texto: "Shanks foi o primeiro dono do Chapéu de Palha." },
  { correto: false, texto: "Shanks nasceu no East Blue." },
  { correto: false, texto: "Shanks tem uma cicatriz no olho direito." },
  { correto: false, texto: "Shiliew é o capitão da terceira frota do Teach." },
  { correto: false, texto: "Shiryu é o capitão da terceira frota do Teach." },
  { correto: false, texto: "Shojo é um membro dos Rumbar Pirates." },
  { correto: false, texto: "Smoker comeu a Doku Doku no Mi." },
  { correto: false, texto: "Smoker é conhecido como Caçador Cinza." },
  { correto: false, texto: "Smoker é usuário do Haki do Armamento apenas." },
  { correto: false, texto: "Smoker nasceu no East Blue." },
  { correto: false, texto: "Squard nasceu em North Blue." },
  { correto: false, texto: "Stussy nasceu no West Blue." },
  { correto: false, texto: "Sugar ficou permanentemente traumatizada com o rosto do Zoro, tornando-se um trauma incurável." },
  { correto: false, texto: "Tamago comeu a Cuma Cuma no Mi, que o permite ciclar em diferentes formas." },
  { correto: false, texto: "Tamago perdeu o olho direito para Pedro." },
  { correto: false, texto: "Todos os quatro principais membros da tripulação do Shanks são do mesmo oceano." },
  { correto: false, texto: "Trafalgar Law comeu a Pika Pika no Mi." },
  { correto: false, texto: "Trafalgar Law é conhecido como o Cirurgião Mortal." },
  { correto: false, texto: "Trafalgar Law é membro dos Piratas do Chapéu de Palha." },
  { correto: false, texto: "Trafalgar Law já foi um escravo." },
  { correto: false, texto: "Trafalgar Law perdeu um braço durante o Timeskip." },
  { correto: false, texto: "Trebol tinha Fruta do Diabo do tipo Logia." },
  { correto: false, texto: "Tsuru comeu a Washe Washe no Mi." },
  { correto: false, texto: "Tsuru nasceu no East Blue." },
  { correto: false, texto: "Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitãp dos Piratas Mad Monk." },
  { correto: false, texto: "Van Augur nasceu no West Blue." },
  { correto: false, texto: "Vasco Shot é o capitão do sétimo navio, liderando a sétima frota do Teach." },
  { correto: false, texto: "Vergo pode cobrir quase seu corpo inteiro com Haki." },
  { correto: false, texto: "Vista nasceu na Grand Line." },
  { correto: false, texto: "Wapol nasceu no North Blue" },
  { correto: false, texto: "Woop Slap é o prefeito de Orange Town." },
  { correto: false, texto: "Zeff perdeu sua perna esquerda para salvar Sanji" },
  { correto: false, texto: "Zoro empunhou menos de 8 espadas diferentes no anime" },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de cortantes para completar a conquista da Alvida." },
  { correto: false, texto: "[GLA] Você precisa vencer com um time de cortantes para completar a conquista dos Piratas da Alvida." },
];
